name: Build and Upload .exe

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 0' # Uruchamianie w każdą niedzielę o północy
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Zaktualizowano do wersji, która obsługuje Node.js 20
      
    - name: Set up Python
      uses: actions/setup-python@v5  # Zaktualizowano do wersji, która obsługuje Node.js 20
      with:
        python-version: '3.x'
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      
    - name: Run installResources.ps1
      shell: pwsh
      run: ./installResources.ps1

    - name: Build .exe
      run: |
        pyinstaller --onefile Json_conwerter.py
      shell: pwsh

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: your-executable
        path: dist/Json_conwerter.exe
